// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq7F9OAwofpa9CtvGhyTgiUBbOcHsSG8E',
    appId: '1:329989824825:android:a7735d96d8a3debc4e08e8',
    messagingSenderId: '329989824825',
    projectId: 'tremsol-app',
    storageBucket: 'tremsol-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANwWods0HZvj3ywsuTspZBCrcmEi2sp8I',
    appId: '1:329989824825:ios:16c45dec8cce6e9b4e08e8',
    messagingSenderId: '329989824825',
    projectId: 'tremsol-app',
    storageBucket: 'tremsol-app.firebasestorage.app',
    androidClientId: '329989824825-7ks0jj9d32f4rb1l20goh6u481kuiok5.apps.googleusercontent.com',
    iosClientId: '329989824825-nmkgb0ojh91cm0fv7g7paduu1hqje671.apps.googleusercontent.com',
    iosBundleId: 'com.tremsol.app',
  );
}
